<a href="https://colab.research.google.com/github/Xavier-ML/Machine-Learning-Data-Science-en-Python-Teoria-y-practica./blob/main/T1_Data_cleaning_python_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import os
from google.colab import files
import io

In [2]:
mainpath = files.upload()

Saving titanic3.csv to titanic3.csv

In [3]:
from pandas.io.common import BytesIO
data_titanic = pd.read_csv(io.BytesIO(mainpath["titanic3.csv"]))

In [4]:
data_titanic.head

<bound method NDFrame.head of       pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton
1          1         1                   Allison, Master. Hudson Trevor
2          1         0                     Allison, Miss. Helen Loraine
3          1         0             Allison, Mr. Hudson Joshua Creighton
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
...      ...       ...                                              ...
1304       3         0                             Zabour, Miss. Hileni
1305       3         0                            Zabour, Miss. Thamine
1306       3         0                        Zakarian, Mr. Mapriededer
1307       3         0                              Zakarian, Mr. Ortin
1308       3         0                               Zimmerman, Mr. Leo

         sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.0000      0      0   24160  211.3375       B5        S    2
1       male   0.9167      1      2  113781  151.5500  C22 C26        S   11
2     female   2.0000      1      2  113781  151.5500  C22 C26        S  NaN
3       male  30.0000      1      2  113781  151.5500  C22 C26        S  NaN
4     female  25.0000      1      2  113781  151.5500  C22 C26        S  NaN
...      ...      ...    ...    ...     ...       ...      ...      ...  ...
1304  female  14.5000      1      0    2665   14.4542      NaN        C  NaN
1305  female      NaN      1      0    2665   14.4542      NaN        C  NaN
1306    male  26.5000      0      0    2656    7.2250      NaN        C  NaN
1307    male  27.0000      0      0    2670    7.2250      NaN        C  NaN
1308    male  29.0000      0      0  315082    7.8750      NaN        S  NaN

       body                        home.dest
0       NaN                     St Louis, MO
1       NaN  Montreal, PQ / Chesterville, ON
2       NaN  Montreal, PQ / Chesterville, ON
3     135.0  Montreal, PQ / Chesterville, ON
4       NaN  Montreal, PQ / Chesterville, ON
...     ...                              ...
1304  328.0                              NaN
1305    NaN                              NaN
1306  304.0                              NaN
1307    NaN                              NaN
1308    NaN                              NaN

[1309 rows x 14 columns]>

In [10]:
filesref = open('Titanic Description.txt', 'r', encoding='windows-1252')
texto = filesref.readlines()
for lineas in texto:
    print(lineas.strip())

filesref.close()

NAME:  titanic3
TYPE:  Census
SIZE:  1309 Passengers, 14 Variables

DESCRIPTIVE ABSTRACT: The titanic3 data frame describes the survival
status of individual passengers on the Titanic.  The titanic3 data
frame does not contain information for the crew, but it does contain
actual and estimated ages for almost 80% of the passengers.

SOURCES: Hind, Philip.  "Encyclopedia Titanica."  Online.  Internet.
n.p.  02 Aug 1999.  Avaliable http://atschool.eduweb.co.uk/phind

VARIABLE DESCRIPTIONS:
pclass          Passenger Class
(1 = 1st; 2 = 2nd; 3 = 3rd)
survival        Survival
(0 = No; 1 = Yes)
name            Name
sex             Sex
age             Age
sibsp           Number of Siblings/Spouses Aboard
parch           Number of Parents/Children Aboard
ticket          Ticket Number
fare            Passenger Fare
cabin           Cabin
embarked        Port of Embarkation
(C = Cherbourg; Q = Queenstown; S = Southampton)
boat            Lifeboat
body            Body Identification Number
home.dest       Home/Destination

SPECIAL NOTES:
Pclass is a proxy for socio-economic status (SES)
1st ~ Upper; 2nd ~ Middle; 3rd ~ Lower

Age is in Years; Fractional if Age less than One (1)
If the Age is Estimated, it is in the form xx.5

Fare is in Pre-1970 British Pounds (£)
Conversion Factors:  1£ = 12s = 240d and 1s = 20d

With respect to the family relation variables (i.e. sibsp and parch)
some relations were ignored.  The following are the definitions used
for sibsp and parch.

Sibling:  Brother, Sister, Stepbrother, or Stepsister of Passenger Aboard Titanic
Spouse:   Husband or Wife of Passenger Aboard Titanic (Mistresses and Fiancées Ignored)
Parent:   Mother or Father of Passenger Aboard Titanic
Child:    Son, Daughter, Stepson, or Stepdaughter of Passenger Aboard Titanic

Other family relatives excluded from this study include cousins,
nephews/nieces, aunts/uncles, and in-laws.  Some children travelled
only with a nanny, therefore parch=0 for them.  As well, some
travelled with very close friends or neighbors in a village, however,
the definitions do not support such relations.

STORY BEHIND THE DATA:
This dataset is based on the Titanic Passenger List edited by Michael
A. Findlay, originally published in Eaton & Haas (1994) Titanic:
Triumph and Tragedy, Patrick Stephens Ltd, and expanded with the help
of the internet community.  The original HTML files were obtained by
Philip Hind (1999).

PEDAGOGICAL NOTES:
This dataset is ideal for teaching basic functions in S-PLUS in the
realm of Statistical Computing and Graphics.  It can also prove useful
in teaching binary logistic regression and methods of imputation, both
single and multiple.  The dataset is also useful for demonstrating
many of the functions available in Frank Harrell's Hmisc library as
well as demonstrating binary logistic regression analysis using the
Design library.

An interesting result may be obtained using functions from the Hmisc
library in S-PLUS

attach(titanic3)
plsmo(age, survived, group=sex, datadensity=T)         # OR group=pclass
plot(naclus(titanic3))                                 # study patterns of missing values
summary(survived ~ age + sex + pclass, data=titanic3)

REFERENCES:
Harrell FE.  "Predicting Outcomes: Applied Survival Analysis and
Logistic Regression."  Book manuscript available from the University
of Virginia Bookstore, 1999.

SUBMITTED BY:
Thomas E. Cason, Undergraduate Research Assistant
Division of Biostatistics and Epidemiology
Department of Health Evaluation Sciences
University of Virginia School of Medicine
Box 600, Charlottesville, VA 22908 USA
Electronic Mail:  tcason@virginia.edu

----------------------------------------------------------------------
FREQUENTLY ASKED QUESTIONS ABOUT THE DATASET

1. For those over age 25 the mean # spouses/siblings is about .34 -
seems a little low

The only explanation I can offer (without a deep search) is the
overwhelming "Third Class Bias" as I call it.  Many third class
passengers travelled alone... or some with friends... which is
not under the umbrella of the sibsp definition.  Also, many 3rd
classers were immigrating to the US... they were married... but
were sent off alone to establish a "foothole" and then later sent
for their spouses... if they survived... most did not.

2. For those under age 14 the mean # parents/children is 1.37 -
seems a bit low

Again... not all children travelled with their parents...
especially in 3rd class.  Some children travelled with older
siblings... nannies... aunts/uncles... etc.  Actually, more often
than not... children travelled with only one parent.

-TEC


After further investigation... I found my initial instincts regarding
the low means to be correct.  There's not much else to say about it...
but I'll cite some unusual passenger cases that may come up in the
future regarding this issue.

Case #1:  Emanuel, Miss. Virginia Ethel... 3d Class... Age 5...
sibsp/parch=0/0
Boarded with her nurse Miss. Elizabeth Dowdell... escorted her to
grandparents' home in New York, NY.

Case #2:  Hassan, Mr. Houssein G N... 3d Class... Age 11...
s/p=0/0
Traveled with family friend Mr. Nassef Cassem Albimona... going
to visit his parents in American from Lebanon.  (Interesting
Note:  Albimona was from Fredericksburg, VA)

Case #3:  Ayoub, Miss. Banoura... 3d Class... Age 13... s/p=0/0
Boarded with 5 cousins... travelling to Detroit, MI to be
reunited with family.

Case #4:  Nasser, Mrs. Nicholas Nasser... 2d Class... Age 14...
s/p=1/0
Married to a 32 year old man... sibsp stands for spouse rather
than sibling... unusual at such a young age.  She lied when she
boarded the Titanic and claimed she was 18... however, her birth
certificate proves that on April 15, 1912 she was 14... not 18!

I hope this provides some insight to a few uncommon instances
where the definitions do not encompass the actual travel status
of a passenger.

There were only one or two instances of family members
"crossing pclass lines"... and they were included and counted for
in sibsp and parch.

-TEC

In [ ]:
data_titanic.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

columns.values muestra las categorias

In [13]:
data_titanic.columns.values

array(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch',
       'ticket', 'fare', 'cabin', 'embarked', 'boat', 'body', 'home.dest'],
      dtype=object)

El siguiente procedimiento es para cambiar las categorias por nombres de otro csv, para un trabajo elaborado dependera de la cantidad de categorias que quieres cambiar.

In [22]:
data_cols = pd.read_csv("Customer Churn Columns.csv")
data_col_list = data_cols["Column_Names"].tolist()

In [30]:
data2 = pd.read_csv("titanic3.csv", names = data_col_list)
data2.columns.values

array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U'], dtype=object)

In [39]:
data2.shape

(1310, 21)

In [35]:
data2.head(4)

,A,B,C,D,E,F,G,H,I,J,...,L,M,N,O,P,Q,R,S,T,U
0,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,...,boat,body,home.dest,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,...,2,NaN,"St Louis, MO",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,...,11,NaN,"Montreal, PQ / Chesterville, ON",NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,0,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.5500,C22 C26,...,NaN,NaN,"Montreal, PQ / Chesterville, ON",NaN,NaN,NaN,NaN,NaN,NaN,NaN

Warning: Total number of columns (21) exceeds max_columns (20) limiting to first (20) columns.

In [36]:
data_titanic.columns.values

array(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch',
       'ticket', 'fare', 'cabin', 'embarked', 'boat', 'body', 'home.dest'],
      dtype=object)

In [37]:
data_titanic.shape

(1309, 14)

### Carga de datos a través de la función open

In [49]:
data3 = open("Customer Churn Model.txt","r")

In [50]:
cols = data3.readline().strip().split(",")
n_cols = len(cols)
n_cols

21

In [51]:
counter = 0
main_dict = {}
for col in cols:
    main_dict[col] = []

In [52]:
for line in data3:
    values = line.strip().split(",")
    for i in range(len(cols)):
        main_dict[cols[i]].append(values[i])
    counter += 1

print("el data set tiene %d filas y %d  columnas" % (counter, n_cols))

el data set tiene 3333 filas y 21  columnas

In [53]:
df3 = pd.DataFrame(main_dict)
df3.head()

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,KS,128,415,382-4657,no,yes,25,265.100000,110,45.070000,...,99,16.780000,244.700000,91,11.010000,10.000000,3,2.700000,1,False.
1,OH,107,415,371-7191,no,yes,26,161.600000,123,27.470000,...,103,16.620000,254.400000,103,11.450000,13.700000,3,3.700000,1,False.
2,NJ,137,415,358-1921,no,no,0,243.400000,114,41.380000,...,110,10.300000,162.600000,104,7.320000,12.200000,5,3.290000,0,False.
3,OH,84,408,375-9999,yes,no,0,299.400000,71,50.900000,...,88,5.260000,196.900000,89,8.860000,6.600000,7,1.780000,2,False.
4,OK,75,415,330-6626,yes,no,0,166.700000,113,28.340000,...,122,12.610000,186.900000,121,8.410000,10.100000,3,2.730000,3,False.

Warning: Total number of columns (21) exceeds max_columns (20) limiting to first (20) columns.

In [59]:
infile = "Customer Churn Model.txt"
outfile = "Tab1 customer churn model.txt"

In [60]:
with open(infile, "r") as infile1:
    with open(outfile, "w") as outfile1:
        for line in infile1:
            fields = line.strip().split(",")
            outfile1.write("\t".join(fields))
            outfile1.write("\n")

In [61]:
df4 = pd.read_csv(outfile, sep = "\t")

In [62]:
df4

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False.
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False.
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False.
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False.
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,414-4276,no,yes,36,156.2,77,26.55,...,126,18.32,279.1,83,12.56,9.9,6,2.67,2,False.
3329,WV,68,415,370-3271,no,no,0,231.1,57,39.29,...,55,13.04,191.3,123,8.61,9.6,4,2.59,3,False.
3330,RI,28,510,328-8230,no,no,0,180.8,109,30.74,...,58,24.55,191.9,91,8.64,14.1,6,3.81,2,False.
3331,CT,184,510,364-6381,yes,no,0,213.8,105,36.35,...,84,13.57,139.2,137,6.26,5.0,10,1.35,2,False.
3332,TN,74,415,400-4344,no,yes,25,234.4,113,39.85,...,82,22.60,241.4,77,10.86,13.7,4,3.70,0,False.

Warning: Total number of columns (21) exceeds max_columns (20) limiting to first (20) columns.

### Leer datos desde una URL

In [14]:
def downloadFromURL(url, filename, sep = ",", delim = "\n", encoding="utf-8"):
    #primero importar la libreria y hacemos conexion con la web de los datos
    #señora de alta alcurnia de grandes apellidos subio al micro de la era donde dice que cobran cupos
    import urllib3
    http = urllib3.PoolManager()
    r = http.request('GET', url)
    print("el estado de la respuesta es %d" %(r.status))
    response = r.data
    
    #el objeto response contiene un string binario asi que lo convertimos a un string descodificandolo en UTF-8
    str_data = response.decode(encoding)
    #dividimos el string en un array de filas separandolo en intros
    lines = str_data.plit(delim)
    #la primera línea contiene la cabecera, así que la extraemos
    col_names = lines[0].split(sep)
    n_cols = len(col_names)
    #Generamos un diccionario vacío donde ira la informacion procesada desde la URL externa
    counter = 0
    main_dic = {}
    for col in col_name:
        main_dict[col] = []
    #Procesamos fila a fila la información para ir rellenando el diccionario con los datos como hicimos antes
    for line in lines:
        #Nos saltamos la primera linea que es la que contiene la cabecera y la tenemos procesada
        if(counter > 0):
            #Dividimos cada string por las comas como elemento separador
            values =  line.strip().split(sep)
            #Añadimos cada valor a su respectiva columna del diccionario
            for i in range(len(col_name)):
                main_dict[col_name[i]].append(values[i])
        counter += 1
    print("El data set tiene %d filas y %d columnas"%(counter, n_cols))
    #convertimos el diccionario procesado a Dataframe y comprobamos que los datos son correctos
    df = pd.DataFrame(main_dict)
    print(df.head())
    #Elegimos donde guardarlo (en la carpeta datasets es donde tiene mas sentido por el contexto del analisis)
    mainpath = r"C:\Users\HOME\Desktop\ML\python-ml-course-master\datasets"
    filename = "work\download"
    fullpath = os.path.join(mainpath, filename)
    
    #lo guaramos en csv, en JSON o en excel según queramos
    df.to_csv(fullpath+".csv")
    df.to_json(fullpath+".json")
    df.to_excel(fullpath+".xls")
    
    return

In [15]:
import requests

res = requests.get('https://www.kaggle.com/c/forest-cover-type-prediction/data?select=test.csv')

print(res)

<Response [200]>

In [16]:
if res:
    print('Response OK')
else:
    print('Response Failed')

Response OK

In [17]:
print(res.headers)

{'Content-Type': 'text/html; charset=utf-8', 'Date': 'Sun, 06 Nov 2022 01:46:32 GMT', 'Cache-Control': 'no-cache, no-store', 'Content-Encoding': 'gzip', 'Pragma': 'no-cache', 'Set-Cookie': 'ka_sessionid=065a50a5d5cda1fb31f661289cfe6647; max-age=2626560; path=/, CSRF-TOKEN=CfDJ8M8bzImQuQVBugV8xw6Jv2sUr7oD8hN-ywHmpzxOReUGXIPD9UphesCLFi4pSMEkGLLeVy3L7BWCi3C9Wb73D9kOActkQIXHmIeazJeUqA; path=/; secure; samesite=lax; httponly, XSRF-TOKEN=CfDJ8M8bzImQuQVBugV8xw6Jv2s0uqDAsfm50KjOtwapfTMv3Nc3hG0S6Sj6I6fNBScRwmh7whcE8VfTKSY-1_vpdJunRKzDwmbpZkzJNXwnkTVofw; path=/; secure; samesite=lax, CLIENT-TOKEN=eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJpc3MiOiJrYWdnbGUiLCJhdWQiOiJjbGllbnQiLCJzdWIiOm51bGwsIm5idCI6IjIwMjItMTEtMDZUMDE6NDY6MzIuOTYxODcxNloiLCJpYXQiOiIyMDIyLTExLTA2VDAxOjQ2OjMyLjk2MTg3MTZaIiwianRpIjoiMzlmZmNmY2QtYjg2Ny00NzQwLWJlNjctNzhiYzE5ZWRlNzhkIiwiZXhwIjoiMjAyMi0xMi0wNlQwMTo0NjozMi45NjE4NzE2WiIsImFub24iOnRydWUsImZmIjpbIktlcm5lbHNSZXN1bWUiLCJLZXJuZWxzRmlyZWJhc2VMb25nUG9sbGluZyIsIktlcm5lbHNTdGFja092ZXJmbG93U2VhcmNoIiwiQ29tbXVuaXR5S21JbWFnZVVwbG9hZGVyIiwiVFBVQ29tbWl0U2NoZWR1bGluZyIsIkFsbG93Rm9ydW1BdHRhY2htZW50cyIsIktlcm5lbHNUNEdQVXMiLCJLTUxlYXJuRGV0YWlsIiwiRnJvbnRlbmRDb25zb2xlRXJyb3JSZXBvcnRpbmciLCJSZWdpc3RyYXRpb25OZXdzRW1haWxTaWdudXBJc09wdE91dCIsIlBob25lVmVyaWZ5Rm9yQ29tbWVudHMiLCJQaG9uZVZlcmlmeUZvck5ld1RvcGljIiwiTGlocE5leHRTdGVwcyIsIkxpaHBOZXh0U3RlcHNNZXRyaWNzIiwiS21Db21wc1N1Ym1pc3Npb25QYWdlIiwiS21Db21wc1N1Ym1pdFBhbmVsIiwiTGVhcm5HdWlkZXMiLCJEYXRhc2V0c01ldGFkYXRhVG9EYXRhVGFiIiwiRGF0YXNldHNWYWxpZGF0ZVVwbG9hZGVkWmlwRmlsZXMiLCJLZXJuZWxFZGl0b3JIYW5kbGVNb3VudE9uY2UiXSwiZmZkIjp7Iktlcm5lbEVkaXRvckF1dG9zYXZlVGhyb3R0bGVNcyI6IjMwMDAwIiwiRnJvbnRlbmRFcnJvclJlcG9ydGluZ1NhbXBsZVJhdGUiOiIwLjAxIiwiRW1lcmdlbmN5QWxlcnRCYW5uZXIiOiJ7IH0iLCJDbGllbnRScGNSYXRlTGltaXQiOiI0MCIsIkZlYXR1cmVkQ29tbXVuaXR5Q29tcGV0aXRpb25zIjoiMzUzMjUsMzcxNzQsMzM1NzksMzc4OTgsMzczNTQsMzc5NTkiLCJBZGRGZWF0dXJlRmxhZ3NUb1BhZ2VMb2FkVGFnIjoiZGF0YXNldHNNYXRlcmlhbERldGFpbCJ9LCJwaWQiOiJrYWdnbGUtMTYxNjA3Iiwic3ZjIjoid2ViLWZlIiwic2RhayI6IkFJemFTeUE0ZU5xVWRSUnNrSnNDWldWei1xTDY1NVhhNUpFTXJlRSIsImJsZCI6ImVlMjZjZDA5NmVjODFiZjkyMGJlMWM1MjJlYzg0YTFiY2NiYThlYjEifQ.; path=/; secure; samesite=lax, GCLB=CIuuxOzPmq_3Pw; path=/; HttpOnly', 'Vary': 'Accept-Encoding', 'Turbolinks-Location': 'https://www.kaggle.com/c/forest-cover-type-prediction/data?select=test.csv', 'X-Frame-Options': 'SAMEORIGIN', 'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload', 'Content-Security-Policy': "object-src 'none'; script-src 'nonce-BjY4QQa7j4ymXw6gfepnXg==' 'report-sample' 'unsafe-inline' 'unsafe-eval' 'strict-dynamic' https: http:; frame-src 'self' https://www.kaggleusercontent.com https://www.youtube.com/embed/ https://polygraph-cool.github.io https://www.google.com/recaptcha/ https://form.jotform.com https://submit.jotform.us https://submit.jotformpro.com https://submit.jotform.com https://www.docdroid.com https://www.docdroid.net https://kaggle-static.storage.googleapis.com https://kaggle-static-staging.storage.googleapis.com https://kkb-dev.jupyter-proxy.kaggle.net https://kkb-staging.jupyter-proxy.kaggle.net https://kkb-production.jupyter-proxy.kaggle.net https://kkb-dev.firebaseapp.com https://kkb-staging.firebaseapp.com https://kkb-production.firebaseapp.com https://kaggle-metastore-test.firebaseapp.com https://kaggle-metastore.firebaseapp.com https://apis.google.com https://content-sheets.googleapis.com/ https://accounts.google.com/ https://storage.googleapis.com https://docs.google.com https://drive.google.com https://calendar.google.com/; base-uri 'none'; report-uri https://csp.withgoogle.com/csp/kaggle/20201130;", 'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'strict-origin-when-cross-origin', 'Via': '1.1 google', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000', 'Transfer-Encoding': 'chunked'}

In [18]:
print(res.text)

<!DOCTYPE html>
<html lang="en">

<head>
  <title>Forest Cover Type Prediction | Kaggle</title>
  <meta charset="utf-8" />
    <meta name="robots" content="index, follow" />
  <meta name="description" content="Use cartographic variables to classify forest categories" />
  <meta name="turbolinks-cache-control" content="no-cache" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0, minimum-scale=1.0">
  <meta name="theme-color" content="#008ABC" />
  <script nonce="BjY4QQa7j4ymXw6gfepnXg==" type="text/javascript">
    window["pageRequestStartTime"] = 1667699192929;
    window["pageRequestEndTime"] = 1667699192961;
    window["initialPageLoadStartTime"] = new Date().getTime();
  </script>
  <link rel="preconnect" href="https://www.google-analytics.com" crossorigin="anonymous" /><link rel="preconnect" href="https://stats.g.doubleclick.net" /><link rel="preconnect" href="https://storage.googleapis.com" /><link rel="preconnect" href="https://apis.google.com" />
  <link href="/static/images/favicon.ico" rel="shortcut icon" type="image/x-icon" />
  <link rel="manifest" href="/static/json/manifest.json" crossorigin="use-credentials">


  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/icon?family=Google+Material+Icons"
    rel="preload" as="style" />
  <link href="https://fonts.googleapis.com/css?family=Inter:400,400i,500,500i,600,600i,700,700i"
    rel="preload" as="style" />
  <link href="https://fonts.googleapis.com/icon?family=Google+Material+Icons"
    rel="stylesheet" media="print" id="async-google-font-1" />
  <link href="https://fonts.googleapis.com/css?family=Inter:400,400i,500,500i,600,600i,700,700i"
    rel="stylesheet" media="print" id="async-google-font-2" />
  <script nonce="BjY4QQa7j4ymXw6gfepnXg==" type="text/javascript">
    const styleSheetIds = ["async-google-font-1", "async-google-font-2"];
    styleSheetIds.forEach(function (id) {
      document.getElementById(id).addEventListener("load", function() {
        this.media = "all";
      });
    });
  </script>

    <link rel="stylesheet" type="text/css" href="/static/assets/vendor.css?v=85d731a494547753f1bf" />
    <link rel="stylesheet" type="text/css" href="/static/assets/app.css?v=8a9781128da31e278b7b" />



      <script nonce="BjY4QQa7j4ymXw6gfepnXg==">
        try{(function(a,s,y,n,c,h,i,d,e){d=s.createElement("style");
        d.appendChild(s.createTextNode(""));s.head.appendChild(d);d=d.sheet;
        y=y.map(x => d.insertRule(x + "{ opacity: 0 !important }"));
        h.start=1*new Date;h.end=i=function(){y.forEach(x => x<d.cssRules.length ? d.deleteRule(x) : {})};
        (a[n]=a[n]||[]).hide=h;setTimeout(function(){i();h.end=null},c);h.timeout=c;
        })(window,document,['.site-header-react__nav'],'dataLayer',2000,{'GTM-52LNT9S':true});}catch(ex){}
    </script>
    <script nonce="BjY4QQa7j4ymXw6gfepnXg==">
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());
        gtag('config', 'UA-12629138-1', {
            'optimize_id': 'GTM-52LNT9S',
            'displayFeaturesTask': null,
            'send_page_view': false,
            'content_group1': 'Competitions'
        });
    </script>
    <script nonce="BjY4QQa7j4ymXw6gfepnXg==" async src="https://www.googletagmanager.com/gtag/js?id=UA-12629138-1"></script>



    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="@kaggle" />
        <meta name="twitter:creator" content="@kaggle" />
    <meta name="og:url" content="https://kaggle.com/competitions/forest-cover-type-prediction" />
    <meta name="og:title" content="Forest Cover Type Prediction" />
    <meta name="og:description" content="Use cartographic variables to classify forest categories" />
    <meta name="og:image" content="https://storage.googleapis.com/kaggle-competitions/kaggle/3936/logos/thumb76_76.png" />


  <meta name="twitter:site" content="@Kaggle" />









<script nonce="BjY4QQa7j4ymXw6gfepnXg==" type="text/javascript">
    var Kaggle = window.Kaggle || {};

    Kaggle.Current = {
        antiForgeryToken: 'CfDJ8M8bzImQuQVBugV8xw6Jv2s0uqDAsfm50KjOtwapfTMv3Nc3hG0S6Sj6I6fNBScRwmh7whcE8VfTKSY-1_vpdJunRKzDwmbpZkzJNXwnkTVofw',
        isAnonymous: true,
        analyticsToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Njc3MDAwOTIsIlVzZXJJZCI6MH0.UK8a5vHtJ84ke65j4bMX_n7Bfi_LYauluMDAfo4umlY',
        analyticsTokenExpiry: 15,








    }
        Kaggle.Current.log = function(){};
        Kaggle.Current.warn = function(){};

    const decodeUserProperty = function (escapedUserProperty) {
        escapedUserProperty = escapedUserProperty || "";
        try {
            const textVersion = new DOMParser().parseFromString(escapedUserProperty, "text/html").documentElement.textContent;
            if (textVersion) {
                return textVersion;
            }
        } catch(ex) {}
        return escapedUserProperty;
    }
    Kaggle.Current.userDisplayName = decodeUserProperty(Kaggle.Current.userDisplayNameEscaped);
    Kaggle.Current.userEmail = decodeUserProperty(Kaggle.Current.userEmailEscaped);
</script>



<script nonce="BjY4QQa7j4ymXw6gfepnXg==" type="text/javascript">
    var Kaggle = window.Kaggle || {};
    Kaggle.PageMessages = [];
</script>



    <script nonce="BjY4QQa7j4ymXw6gfepnXg==">window['useKaggleAnalytics'] = true;</script>

  <script id="gapi-target" nonce="BjY4QQa7j4ymXw6gfepnXg==" src="https://apis.google.com/js/api.js" defer
    async></script>
  <script nonce="BjY4QQa7j4ymXw6gfepnXg==" src="/static/assets/runtime.js?v=f74f1b180b465e326876" data-turbolinks-track="reload"></script>
  <script nonce="BjY4QQa7j4ymXw6gfepnXg==" src="/static/assets/vendor.js?v=7357fda0a7a62b62514d" data-turbolinks-track="reload"></script>
  <script nonce="BjY4QQa7j4ymXw6gfepnXg==" src="/static/assets/app.js?v=73ab888ab7262bb6969e" data-turbolinks-track="reload"></script>
    <script nonce="BjY4QQa7j4ymXw6gfepnXg==" type="text/javascript">
      window.kaggleStackdriverConfig = {
        key: 'AIzaSyA4eNqUdRRskJsCZWVz-qL655Xa5JEMreE',
        projectId: 'kaggle-161607',
        service: 'web-fe',
        version: 'ci',
        userId: '0'
      }
    </script>
</head>

<body data-turbolinks="false">
  <main>







<div id="site-container"></div>
<div data-component-name="NavigationContainer" style="display: flex; flex-direction: column; flex: 1 0 auto;"></div><script class="kaggle-component" nonce="BjY4QQa7j4ymXw6gfepnXg==">var Kaggle=window.Kaggle||{};Kaggle.State=Kaggle.State||[];Kaggle.State.push({"navigationType":"BOTH_NAV"});performance && performance.mark && performance.mark("NavigationContainer.componentCouldBootstrap");</script>
<div id="site-body" class="hide">


